

INSERT INTO categories(ID,CATEGORY_NAME)
 VALUES (1,'CLOTHES');
 
 INSERT INTO categories(ID,CATEGORY_NAME)
 VALUES (2,'ELECTRONICS');
 
INSERT INTO categories(ID,CATEGORY_NAME)
 VALUES (3,'PERSONAL CARE');
  
INSERT INTO categories(ID,CATEGORY_NAME)
 VALUES (4,'HOME & KITCHEN');

INSERT INTO categories(ID,CATEGORY_NAME)
 VALUES (5,'SPORTS & FITNESS');

commit;



INSERT INTO products(PRODUCT_NAME,PRICE,CATEGORY_ID,PRODUCT_DSCR) VALUES('Shirts',1350.0,1,'Mens Denim Shirt'); 
INSERT INTO products(PRODUCT_NAME,PRICE,CATEGORY_ID,PRODUCT_DSCR) VALUES('Dumbells',3150.0,5,'Decathlon Brand');
INSERT INTO products(PRODUCT_NAME,PRICE,CATEGORY_ID,PRODUCT_DSCR) VALUES('Laptop',56050.0,2,'Lenovo Thinkpad'); 
INSERT INTO products(PRODUCT_NAME,PRICE,CATEGORY_ID,PRODUCT_DSCR) VALUES('Gas Stove',4300.0,4,'Pigeon Cookware'); 
INSERT INTO products(PRODUCT_NAME,PRICE,CATEGORY_ID,PRODUCT_DSCR) VALUES('Copper Chimney',3500.0,4,'Faber automatic Chimney'); 
INSERT INTO products(PRODUCT_NAME,PRICE,CATEGORY_ID,PRODUCT_DSCR) VALUES('Dove Shampoo',35.0,3,'Hindustan Uniliver Product'); 
INSERT INTO products(PRODUCT_NAME,PRICE,CATEGORY_ID,PRODUCT_DSCR) VALUES('Jeans',1700.0,1,'Mufti Jeans'); 

commit;